### ISSUE TITLE
Dynamically infer available shields instead of `--disable-safety`

### ISSUE THREAD

**Issue by yanxi0830** [meta-llama/llama-stack-apps#110]
### 🚀 The feature, motivation and pitch

Our agent's client have `--disable-safety` flag to enable/disable running shields. This is helpful if user do not have shields served on server. 

Optimize this flag and dynamically check against available shields for running safety, and use that to determine whether shields should be run.

**Comment by rabelmervin** [comment]
Hi @yanxi0830 I would like to contribute to this issue could you please assign me ? Any guidance would be appreciated 👍
