### ISSUE TITLE
Several Arguments Seems Missing in llama-toolchain, according to your document

### ISSUE THREAD

**Issue by jnzju** [meta-llama/llama-stack-apps#70]
When building up the project according to your ''Installing and Configuring Distributions'' section, the following error occurs:

```
llama stack build local --name 8b-instruct
usage: llama [-h] {download,model,stack} ...
llama: error: unrecognized arguments: local --name 8b-instruct
```

```
llama stack build local-ollama --name 8b-instruct
usage: llama [-h] {download,model,stack} ...
llama: error: unrecognized arguments: local-ollama --name 8b-instruct
```

Also, I noticed that the ''api'' subcommand is missing. Is it because some components of the [llama-stack](https://github.com/meta-llama/llama-stack) repository are still incomplete?

**Comment by dltn** [comment]
Thanks for the report, @jnzju! @yanxi0830 updated these docs; let us know if you need more help
