### ISSUE TITLE
config.json not found

### ISSUE THREAD

**Issue by Amrosx** [meta-llama/llama-stack-apps#84]
`.llama/checkpoints/Llama-Guard-3-8B does not appear to have a file named config.json. Checkout 'https://huggingface.co//home/user/.llama/checkpoints/Llama-Guard-3-8B/tree/None' for available files.`

I have download it from this link `llama download --source meta --model-id Prompt-Guard-86M --meta-url META_URL`
but it looks missing the config.json file

├── checklist.chk
├── consolidated.00.pth
├── LICENSE
├── params.json
├── README.md
└── tokenizer.model

the model was big 15GB and I waited so long . do you have a way run this 

 `llama stack run local-ollama --port 5000 --disable-ipv6`

**Comment by yanxi0830** [comment]
We have recently made updates to address this issue. `Llama-Guard-3-8B` and all Llama models will now share same inference code. 

If you don't need safety shields guard, you could remove the safety configuration from stack run.yaml config, and use `--disable-safety` flag when running app examples.
